# Generated by Django 5.2.13 on 2026-04-09 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asr_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audiofile',
            field=models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
